// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://iodltsabwyvuxxudxzky.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvZGx0c2Fid3l2dXh4dWR4emt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNzU2OTcsImV4cCI6MjA5MTg1MTY5N30.IfFNW_SkMtUUChQ4IG3cZErZjTuCcVuv7eIEsjkG4l4';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Em ambientes sem ENV (ex.: build do Vercel sem variáveis), evitamos quebrar o build.
// No runtime, qualquer uso do cliente sem ENV válidas mostrará um erro claro.
export const supabase = ((): any => {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    // eslint-disable-next-line no-console
    console.error('Supabase env vars não configuradas. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY.');
    return new Proxy({}, {
      get() {
        throw new Error('Supabase não configurado. Defina VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY no ambiente.');
      }
    }) as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
})();